version: '3.9'

services:
  web:
    restart: always
    build:
      dockerfile: ./Dockerfile.sample
    platform: linux/amd64
    ports:
      - 8080:8080

    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 300m
        reservations:
          memory: 100m
          cpus: '0.25'
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  reg_data:
  reg_certs:
  reg_auth:
