version: '3.9'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  web:
    restart: always
    depends_on:
      - nginx
    build:
      dockerfile: ./Dockerfile.sample
    platform: linux/amd64

    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 300m
        reservations:
          memory: 100m
          cpus: '0.25'
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  reg_data:
  reg_certs:
  reg_auth:
